### ISSUE TITLE
[TODO]: Tracker

### ISSUE THREAD

**Issue by kokonut27** [TheAmazonGuy/phoenix#1]
# Todo list:

* [ ] Finish Discord bot
  * [ ] Add moderation & security
  * [ ] Add slash commands
    * [ ] Add game commands
    * [ ] Add meme/picture commands
    * [ ] In-game-currency commands
    * [ ] Add server and profile information commands
* [ ] Finish API
  * [ ] Add picture API
  * [ ] Add weather API
  * [ ] Add database API
  * [ ] Add phoenix API (holds phoenix information and data)

**Comment by aidanw-dev** [comment]
It's only for the api I am not going to add moderation cmds
